stages:
  process_data:
    cmd: python src/process.py
    deps:
      - data/raw/customer_support_tickets.csv
      - src/process.py
    params:
      - process.raw_file
    outs:
      - data/processed/
  train_test_split:
    cmd: python src/train_test_split.py
    deps:
      - data/processed/customer_support_tickets_processed.csv
      - src/train_test_split.py
    params:
      - train_test_split.test_size
    outs:
      - data/training
      - data/testing
  train:
    cmd: python src/train.py
    deps:
      - data/training/training.csv
      - src/train.py
    params:
      - train.training_file
      - train.output_file
    outs:
      - models/model.pkl:
          persist: true
  evaluate:
    cmd: python src/evaluation.py
    deps:
      - models/model.pkl
      - src/evaluation.py
      - data/testing/test.csv
    params:
      - evaluate.model_file
      - evaluate.test_file
    metrics:
      - metrics/test_metrics.json:
          persist: true