stages:
  process_data:
    cmd: python src/process.py
    deps:
      - data/raw/customer_support_tickets.csv
      - src/process.py
    params:
      - process.raw_file
    outs:
      - data/processed/