process:
  raw_file: "data/raw/customer_support_tickets.csv"
train_test_split:
  processed_file: "data/processed/customer_support_tickets_processed.csv"
  test_size: .33
train:
  training_file: "data/training/training.csv"
  output_file: "models/model.pkl"
evaluate:
  model_file: "models/model.pkl"
  test_file: "data/testing/test.csv"